### ISSUE TITLE
Info Page Not Working (Animixplay is down forever).

### ISSUE THREAD

**Issue by reyangurjar** [debsishu/Miyou-FrontEnd#10]
Bro info page is not working. So you have to fix it soon. I think it's not a coincidence that this issue got when animixplay went down.

So happy working.

**Comment by debsishu** [comment]
Yeah, I'm searching for a workaround. It might take some time.

**Comment by jeydinpham** [comment]
My old version of this repo before the v1.0.0 release still works wat

**Comment by reyangurjar** [comment]
> Yeah, I'm searching for a workaround. It might take some time.

Bro i found something.

This api called enime by consumet gives you fetch gogoanime episodes and it's fast (max time = 750 ms, min time = 200ms).

It also works with mal. Like this= 
https://api.enime.moe/mapping/mal/33486

**Comment by debsishu** [comment]
> My old version of this repo before the v1.0.0 release still works wat

Yeah, that would work fine I guess because that was entirely dependent on GogoAnime, But the new release used some parts of AnimixPlay

**Comment by debsishu** [comment]
> Bro info page is not working. So you have to fix it soon. I think it's not a coincidence that this issue got when animixplay went down.
> 
> So happy working.

I've fixed the backend for now. Now it is working fine. Might have to change some things later. This is not as fast as before but It is what it is😑. If you find any new bugs feel free to open a new issue.

**Comment by debsishu** [comment]
> > Yeah, I'm searching for a workaround. It might take some time.
> 
> Bro i found something.
> 
> This api called enime by consumet gives you fetch gogoanime episodes and it's fast (max time = 750 ms, min time = 200ms).
> 
> It also works with mal. Like this= https://api.enime.moe/mapping/mal/33486

Yeah, It is good but does not support dub.
