### ISSUE TITLE
Hey ,can i convert your react app into next js??

### ISSUE THREAD

**Issue by reyangurjar** [debsishu/Miyou-FrontEnd#11]
Bro , i have not contributed to any project ever. So i thought it would be good to start with this. May i convert your react website into next js. And btw i also tried to made my own website using your design . 
 This is the url of that website, and yes i also want your discord id if you have that.
[https://anime-gate.vercel.app/](url)

**Comment by debsishu** [comment]
I've never tried Next.js. You can certainly try. 

discord : Louis2256#6786
