### ISSUE TITLE
any backends I can implement the frontend with?

### ISSUE THREAD

**Issue by HelpmeBOTS** [debsishu/Miyou-FrontEnd#14]
I fully understand that you dont want to release the backend
seeing as though a website as big as animixplay stole it (i think)
without any form of credits 
but I wanna host this fire frontend but my brain is too small
I know there are open sourced gogoapi's but im stupid and 
dont know how to use them

**Comment by HelpmeBOTS** [comment]
also you can implement arc.io to make some money without ads

**Comment by jeydinpham** [comment]
Animixplay stole it? Animixplay shut down anyways 🤡

**Comment by debsishu** [comment]
> I fully understand that you dont want to release the backend seeing as though a website as big as animixplay stole it (i think) without any form of credits but I wanna host this fire frontend but my brain is too small I know there are open sourced gogoapi's but im stupid and dont know how to use them

No there are no as such ready-to-use public API's to use with this frontend.
