### ISSUE TITLE
Player not working

### ISSUE THREAD

**Issue by TropicLegend** [debsishu/Miyou-FrontEnd#15]
Player is not working because of some CORS policy problem.
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://blablabla  (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘https://anihdplay.com’).

**Comment by TropicLegend** [comment]
Btw, I love the Design of the front end

**Comment by debsishu** [comment]
Yeah, I'm aware of that issue for quite a while now. For this I have to make a proxy server. But I don't think I'll be able to fix this issue anytime soon. I don't get much time after my full-time job to work on my side projects.
