### ISSUE TITLE
Self-hosted API

### ISSUE THREAD

**Issue by TropicLegend** [debsishu/Miyou-FrontEnd#17]
How can I self-host the Miyou API?
I'd like to take some load off your servers. Also, I like to host stuff myself.

**Comment by TropicLegend** [comment]
Just saw it at the bottom of the README. I don't intend to remove any credits to you. I will show you the URL where I host the anime platform as well and you can check up on it.

**Comment by csebascas** [comment]
It would be great to publicize the backend. I'm sure some people would take it with no credit but the vast majority of us would do nothing like that. I am pretty passionate about Miyou, and it would be cool to see how it works!

**Comment by jeydinpham** [comment]
Fr how did you change the link to numbers
