### ISSUE TITLE
Fast forward button for mobile

### ISSUE THREAD

**Issue by ghost** [debsishu/Miyou-FrontEnd#3]
Is there a way to add fast forward buttons to mobile 
On desktop you can press the right and left arrow keys to skip or rewind 10s but I don't see a way to do that on mobile

**Comment by debsishu** [comment]
> Is there a way to add fast forward buttons to mobile On desktop you can press the right and left arrow keys to skip or rewind 10s but I don't see a way to do that on mobile

added it and also added full screen intro skip button

**Comment by ghost** [comment]
I just read the plyr docs, sorry for asking so much 😔

**Comment by debsishu** [comment]
> I just read the plyr docs, sorry for asking so much 😔

that's fine😄
