### ISSUE TITLE
Cant seem to load

### ISSUE THREAD

**Issue by itz-dude** [debsishu/Miyou-FrontEnd#4]
where are you hosting it for me after hosting it on vercel i cant see and content loading

**Comment by debsishu** [comment]
> where are you hosting it for me after hosting it on vercel i cant see and content loading

I have CORS enabled in the backend so it is not allowing access from your domain
I have added localhost:3000 in CORS white list. So if you run locally it will work. But if you want to host it you have to change the backend CORS white list and host that too

**Comment by itz-dude** [comment]
> > where are you hosting it for me after hosting it on vercel i cant see and content loading
> 
> I have CORS enabled in the backend so it is not allowing access from your domain I have added localhost:3000 in CORS white list. So if you run locally it will work. But if you want to host it you have to change the backend CORS white list and host that too

oh
can you tell me what to edit?

**Comment by debsishu** [comment]
> > > where are you hosting it for me after hosting it on vercel i cant see and content loading
> > 
> > 
> > I have CORS enabled in the backend so it is not allowing access from your domain I have added localhost:3000 in CORS white list. So if you run locally it will work. But if you want to host it you have to change the backend CORS white list and host that too
> 
> oh can you tell me what to edit?

Fork the backend repo and add .env file in the root directory and edit the .env file as I've have written from the readme.md
