### ISSUE TITLE
manga

### ISSUE THREAD

**Issue by itz-dude** [debsishu/Miyou-FrontEnd#7]
you should make a website for manga

**Comment by jeydinpham** [comment]
What would you even call it lmao

**Comment by debsishu** [comment]
> you should make a website for manga

I don't really read Manga, and I don't think I can make a Manga site because I don't know how to structure the site.

**Comment by jeydinpham** [comment]
I think it could be structured the exact same way as Miyou, except you would get data from another source and have to make a reader page instead of the WatchAnime page

**Comment by itz-dude** [comment]
> I think it could be structured the exact same way as Miyou, except you would get data from another source and have to make a reader page instead of the WatchAnime page

yah right

**Comment by itz-dude** [comment]
> a

sad i thought it would be good for a manga site

**Comment by debsishu** [comment]
> I think it could be structured the exact same way as Miyou, except you would get data from another source and have to make a reader page instead of the WatchAnime page

I'll try to make a prototype in Figma in my free time and also I have to find some good manga sources to scrape then.

**Comment by itz-dude** [comment]
> > I think it could be structured the exact same way as Miyou, except you would get data from another source and have to make a reader page instead of the WatchAnime page
> 
> I'll try to make a prototype in Figma in my free time and also I have to find some good manga sources to scrape then.

if you want i can give you list of websites which have good amount of manga and fast updates

**Comment by debsishu** [comment]
> > > I think it could be structured the exact same way as Miyou, except you would get data from another source and have to make a reader page instead of the WatchAnime page
> > 
> > 
> > I'll try to make a prototype in Figma in my free time and also I have to find some good manga sources to scrape then.
> 
> if you want i can give you list of websites which have good amount of manga and fast updates

Yeah, post it here.

**Comment by itz-dude** [comment]
> > > > I think it could be structured the exact same way as Miyou, except you would get data from another source and have to make a reader page instead of the WatchAnime page
> > > 
> > > 
> > > I'll try to make a prototype in Figma in my free time and also I have to find some good manga sources to scrape then.
> > 
> > 
> > if you want i can give you list of websites which have good amount of manga and fast updates
> 
> Yeah, post it here.

ohk so here i go:
https://manganato.com/ (has good and large database)
https://mangaowl.to/ (this is good too)
https://1stkissmanga.io/ (has good database for romance manga)
https://manga18.club/ (good and fast updates for pornwha)
https://toonily.com/ (good database and fast updates for pornwha)
